"use client";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AutoSlider from "@/components/AutoSlider";
import Link from "next/link";

const products = [["Audio","Noise-cancelling headphones","$99.99","https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=600"],["Work","Precision workspace gear","$129.99","https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=600"],["Home","Objects with a point of view","$79.99","https://images.pexels.com/photos/325876/pexels-photo-325876.jpeg?auto=compress&cs=tinysrgb&w=600"]];

export default function Page(){return <div className="min-h-screen bg-[#08070d] text-white"><Navbar/><main>
  <section className="purple-grid relative isolate min-h-[48rem] overflow-hidden px-5 pb-20 pt-36 sm:px-8 lg:min-h-[52rem]"><div className="absolute -left-40 top-24 h-[34rem] w-[34rem] rounded-full bg-purple-700/25 blur-[130px]"/><div className="absolute right-0 top-0 h-[30rem] w-[30rem] rounded-full bg-fuchsia-600/15 blur-[120px]"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div className="pt-8"><p className="eyebrow mb-6 text-xs font-medium text-purple-300">Elevated everyday / 01</p><h1 className="display-font max-w-3xl text-5xl font-bold leading-[.98] tracking-[-.05em] sm:text-7xl lg:text-8xl">Objects worth <span className="bg-gradient-to-r from-purple-300 to-fuchsia-400 bg-clip-text text-transparent">keeping.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-zinc-300">A considered collection of technology, style, and home essentials—selected for the way you want to live.</p><div className="mt-10 flex flex-wrap items-center gap-4"><Link href="/shop" className="glow-button rounded-full px-7 py-4 font-bold text-white transition hover:-translate-y-1">Shop the collection <span className="ml-2">→</span></Link><a href="#featured" className="rounded-full border border-white/15 px-7 py-4 font-semibold text-zinc-200 transition hover:border-purple-400 hover:text-white">Explore highlights</a></div><div className="mt-16 flex gap-9 border-t border-white/10 pt-7 text-sm"><div><b className="block text-xl text-white">24h</b><span className="text-zinc-400">Quick dispatch</span></div><div><b className="block text-xl text-white">4.9/5</b><span className="text-zinc-400">Customer rating</span></div><div><b className="block text-xl text-white">30-day</b><span className="text-zinc-400">Easy returns</span></div></div></div><div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-5 rounded-[2.5rem] bg-gradient-to-br from-purple-500/40 to-transparent blur-2xl"/><img className="relative aspect-[4/5] w-full rounded-[2rem] border border-white/15 object-cover shadow-2xl shadow-black/60" src="https://images.pexels.com/photos/3965545/pexels-photo-3965545.jpeg?auto=compress&cs=tinysrgb&w=1100" alt="Premium lifestyle products"/><div className="glass-panel absolute -bottom-5 -left-3 rounded-2xl px-5 py-4 backdrop-blur-xl"><p className="eyebrow text-[10px] text-purple-300">Just arrived</p><p className="mt-1 font-bold">The midnight edit</p></div></div></div></section>
  <section id="featured" className="bg-[#0d0b13] px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow text-xs text-purple-300">Featured / 02</p><h2 className="display-font mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Made for your orbit.</h2></div><Link href="/shop" className="text-sm font-bold text-purple-300 hover:text-purple-100">View all products →</Link></div><AutoSlider/></div></section>
  <section className="px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><div className="mb-12"><p className="eyebrow text-xs text-purple-300">Editor’s selection / 03</p><h2 className="display-font mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Less noise. Better things.</h2></div><div className="grid gap-5 md:grid-cols-3">{products.map(([type,name,price,image])=><article key={name} className="group overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#13111b] transition duration-300 hover:-translate-y-2 hover:border-purple-400/60"><div className="relative overflow-hidden"><img src={image} alt={name} className="h-72 w-full object-cover transition duration-700 group-hover:scale-110"/><span className="absolute left-4 top-4 rounded-full bg-black/60 px-3 py-1 text-xs font-bold backdrop-blur">{type}</span></div><div className="p-6"><h3 className="display-font text-xl font-bold">{name}</h3><div className="mt-5 flex items-center justify-between"><span className="font-semibold text-purple-300">{price}</span><Link href="/shop" className="rounded-full bg-white/8 px-4 py-2 text-sm font-bold transition hover:bg-purple-600">View item</Link></div></div></article>)}</div></div></section>
  <section className="px-5 pb-24 sm:px-8"><div className="mx-auto max-w-7xl rounded-[2rem] border border-purple-400/20 bg-gradient-to-br from-[#251343] via-[#161024] to-[#0e0b15] px-7 py-14 sm:px-14"><p className="eyebrow text-xs text-purple-300">The MetaMart promise</p><div className="mt-8 grid gap-10 md:grid-cols-3">{[["01","Thoughtful selection","A sharper selection in place of an endless scroll."],["02","Fast, clear delivery","Straightforward tracking from checkout to doorstep."],["03","Here when needed","Human support and returns without the maze."]].map(([n,h,p])=><div key={n}><b className="display-font text-3xl">{n}</b><h3 className="mt-4 text-lg font-bold">{h}</h3><p className="mt-2 leading-7 text-zinc-400">{p}</p></div>)}</div></div></section>
</main><Footer/></div>}
